# the path and file name of the keepass database
database_path: /gast-drive-d/MyDatabase.kdbx

# the default output for the password, can be 'stdout' or 'clipboard'
default_output: "stdout"

# file which contains the password to open the keepass db
password_file: ""
# or
# the path to the executable, that returns the password to open the keepass database
password_executable: get-keepass-mydb-master-password.sh