name: Release-RH-Ubi7

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: registry.access.redhat.com/ubi7/ubi:latest

    steps:
      - name: Install dependencies
        run: |
          yum -y install centos-release-scl
          yum -y install devtoolset-9
          scl enable devtoolset-9 bash
          yum -y update
          yum -y install glibc glibc-common glibc-devel glibc-headers libstdc++ libstdc++-devel libX11-devel
          yum -y install gcc gcc-c++ make

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: jaegdi/kpasscli
          token: ${{ secrets.RELEASE_BUILD }}
          ssh-strict: true
          persist-credentials: true
          clean: true
          fetch-depth: 1
          lfs: false
          submodules: false
          set-safe-directory: true

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Build
        run: go build -v -o dist

      - name: Run tests
        run: go test -v ./...

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_BUILD }}
        with:
          tag_name: ${{ github.ref }}-ubi7
          release_name: Release ${{ github.ref }} ubi7
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_BUILD }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/kpasscli
          asset_name: kpasscli-rhel7
          asset_content_type: application/octet-stream
