name: Go

on:
  pull_request:
  push:
    tags-ignore:
      - 'v*'
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23.7'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libx11-dev

    - name: Build
      run: go build -v -o dist/linux-amd64
      
    - name: Check build result
      run: ls -l dist/linux-amd64

    - name: Run tests
      run: go test -v 

