name: Create Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags

jobs:
  build:
    runs-on: rhel-7
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23.7'

    - name: Install dependencies
      run: |
        sudo yum update -y
        sudo yum install -y libx11-dev

    - name: Build
      run: |
        go mod tidy
        go build -v -o dist

    - name: Run tests
      run: go test -v ./...

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/kpasscli

